version: 0.0
Resources:
  - myFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "HelloWorld"
        Alias: "HelloWorldAlias"
        CurrentVersion: "{{CurrentVersion}}"
        TargetVersion: "{{TargetVersion}}"
