version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install pytest
    pre_build:
        commands:
            - python -m pytest test_lambda.py
    build:
        commands:
            - sam package --template-file template.yml --s3-bucket codepipeline-ap-southeast-2-362854396806 --output-template-file package.yml
artifacts:
    files:
        - package.yml
