version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install pytest
    pre_build:
        commands:
            - python -m pytest test_lambda.py
artifacts:
    files:
        - package.yml
